name: dotnet

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

concurrency:
  group: ci-${{ github.base_ref || github.ref_name }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore dependencies
        run: dotnet restore "SharpServiceCollection.slnx" --locked-mode

      - name: Build
        run: dotnet build "SharpServiceCollection.slnx" --configuration Release --no-restore

      - name: Run tests
        run: dotnet test "SharpServiceCollection.slnx" --configuration Release --no-build --no-restore --verbosity normal
